apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: cl-events-frontend
  namespace: flux-system
spec:
  image: ghcr.io/neuland-ingolstadt/campus-life-events-frontend
  interval: 10m
  secretRef:
    name: ghcr-secret
