apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cl-events-db-postgres-pvc
  namespace: verein-ext
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
