apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: outline-db-claim-pvc
  namespace: verein-int
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 400Mi
