apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: outline-storage-pvc-claim-new
  namespace: verein-int
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
