---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloud-eggl-one-cert
  namespace: verein-int
spec:
  secretName: cloud-eggl-one-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - cloud.eggl.one
