apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nextcloud
  namespace: verein-int
spec:
  interval: 24h
  url: https://nextcloud.github.io/helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: verein-int
spec:
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: verein-int
      interval: 12h
  values:
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: cloud.eggl.one
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - cloud.eggl.one
          secretName: cloud-eggl-one-tls
    nextcloud:
      host: cloud.eggl.one
      existingSecret:
        enabled: true
        secretName: nextcloud-secrets
        usernameKey: admin-username
        passwordKey: admin-password
      objectStore:
        s3:
          enabled: true
          existingSecret: nextcloud-secrets
          prefix: nextcloud/
          secretKeys:
            host: s3-host
            accessKey: s3-access-key
            secretKey: s3-secret-key
            bucket: s3-bucket
      extraEnv:
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: nextcloud-secrets
              key: oidc-client-id
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: nextcloud-secrets
              key: oidc-client-secret
        - name: OIDC_ISSUER_URL
          value: https://sso.informatik.sexy/application/o/nextcloud/
