apiVersion: batch/v1
kind: CronJob
metadata:
  name: nextcloud-preview-generator
  namespace: verein-int
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: preview-generator
              image: nextcloud:33.0.0-apache
              command:
                - php
                - /var/www/html/occ
                - preview:pre-generate
              volumeMounts:
                - name: nextcloud-main
                  mountPath: /var/www/html
                  subPath: html
                - name: nextcloud-main
                  mountPath: /var/www/html/data
                  subPath: data
                - name: nextcloud-main
                  mountPath: /var/www/html/config
                  subPath: config
                - name: nextcloud-main
                  mountPath: /var/www/html/custom_apps
                  subPath: custom_apps
                - name: nextcloud-main
                  mountPath: /var/www/tmp
                  subPath: tmp
              resources:
                requests:
                  cpu: 250m
                  memory: 256Mi
                limits:
                  cpu: "1"
                  memory: 1Gi
          volumes:
            - name: nextcloud-main
              persistentVolumeClaim:
                claimName: verein-int-nextcloud-nextcloud
