---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eggl-one-wildcard
  namespace: verein-ext
spec:
  secretName: eggl-one-wildcard-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - eggl.one
  - "*.eggl.one"
  - "*.app.eggl.one"
  - "*.ersti.eggl.one"
  