apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 30m
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 30m
  targetNamespace: monitoring
  releaseName: loki
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: loki
      version: 6.7.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  values:
    deploymentMode: SingleBinary
    loki:
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      auth_enabled: false
      schemaConfig:
        configs:
          - from: "2025-01-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      storage_config:
        filesystem:
          directory: /var/loki/chunks
      limits_config:
        volume_enabled: true
      pattern_ingester:
        enabled: true
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 3Gi
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
      resources:
        limits:
          cpu: 2000m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi
    write:
      replicas: 0
    read:
      replicas: 0
    backend:
      replicas: 0
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    gateway:
      enabled: true
      replicas: 1
