apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 30m
  targetNamespace: monitoring
  releaseName: promtail
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: promtail
      version: 6.16.6
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  values:
    serviceMonitor:
      enabled: false
    config:
      clients:
        - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
      snippets:
        pipelineStages:
          - cri: {}
        scrapeConfigs: |
          - job_name: kubernetes-pods
            pipeline_stages:
              {{- toYaml .Values.config.snippets.pipelineStages | nindent 4 }}
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_node_name]
                target_label: node_name
              - source_labels: [__meta_kubernetes_namespace]
                target_label: namespace
              - source_labels: [__meta_kubernetes_pod_name]
                target_label: pod
              - source_labels: [__meta_kubernetes_pod_container_name]
                target_label: container
              - replacement: /var/log/pods/*$1/*.log
                separator: /
                source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
                target_label: __path__
              - action: replace
                replacement: $1
                source_labels: [__meta_kubernetes_pod_label_name]
                target_label: app
              - action: replace
                source_labels: [__meta_kubernetes_pod_label_app]
                target_label: app
              - action: replace
                source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
                target_label: app
              - action: replace
                source_labels: [__meta_kubernetes_pod_label_release]
                target_label: release
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi

