apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tileserver-data
  namespace: neuland-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
