apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: neuland-api-prod
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: neuland-api-prod
  policy:
    numerical:
      order: asc
  filterTags:
    pattern: '^main-([0-9]+)$'
    extract: '$1'
