apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: neuland-api-prod
  namespace: flux-system
spec:
  image: ghcr.io/neuland-ingolstadt/neuland.app-backend
  interval: 10m
  secretRef:
    name: ghcr-secret

  