apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - sealed-secret.yaml
