apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fider-db-pvc
  namespace: verein-int
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
