apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - ingress.yaml
  - sealed-secret.yaml
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: hedgedoc
