---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hedgedoc-secrets
  namespace: verein-int
spec:
  encryptedData:
    OAUTH2_CLIENT_ID: AgBIhpGT0mDYC8lMeIduSKXx8LjaT4SCeAHE+8ppClkdSHaBABlU3FNf2fg5muYl3G0r9ce9ChlPnVjhptL5jCfBT1zYRrpSK8JvXfZZd8JGmBCr7Qz01w/mXFl4NetlqXrc8wf3lVG0SIXdJ34gqRAknhl9USpwvm4mMCcrZ3zwHrV9TAMygcRTRmvhlMz9dzkHW8uq4CPc/s2vHuHLVMz3GS3ufJyg/WMAdEGOeEqQG7qdDUxzzVzbKMtPPsLqfL8mGSsbMmhutajgQ8zcOhTxWogz+yy7mkx6oZM9UAyVOlD5IroW8x9yVuinSpev7Yb6RYXzCZWteaOWKuuyZ+uXhqurKg2U6b9kl5nGAgyBaFc9dRV2+N8acvT6jllGyPE7vSzOFyx6rMMyuJRGOHjBy9hwW4+xcKdLV/QT1ycZwGtfwGbSyKa/qLfLdfG2ErDYjOvjKkNsn3EaWIwM9uxuFRoz69h7CXwfW9bplVe9Sbi3WqfskmgQzgVHD0lV8ewIvSOzbeLbinR6FHTptRXnC1f2RLUh+LG32FwJqB4I9zrIQ/2RfuXVjQdn8HSYtarbdr4AxnaBbowR8S9jqlqtc+l82hNuZnMPBSKXtzFMwpB0j4XbGQDzC6/mcdVjFM07ZHscLRmAxB9CBAc7V7HYXmRpdU+qgzQgtctTIIuUD5DmJxc0EuH1fL+HOpYNgLEwadmhgOpJ3eJh0vAkcWSnf64=
    OAUTH2_CLIENT_SECRET: AgAruDZo421GpkCUaQJAV6+WnVvi3hH7G5g8rQI5CdQmyzuHM0zBN6GOnwVQCCeQNQLbEdziKxucig8hhTFg425angu1dfBPlKUgBTgBJWpzsKAyrbzPuKpNvlR1wdMbbdc/QQYyVE3Uaj9wTeD6zUVYycnlsrU6TMhJg+ffPBsaPZma2llFOPe8t6VvsKgiTt4JPZPNMGqcBM/2J4UnkCVASMRHFsg4zEbUlIIQlkmD3e41yRU0wqR50bmvCDbstSyRBCw1snTRe6bloRT26PV9uAFd2lJSmPhGAAOrtRoUOpVESrVH3bW0xwO3vcUtJx6aTwTbbUFlX4jmng8PJZFsfUjjP9aCsJ0Ll2Kl4G3vs4Yl+nAeE6X4Jv4dkILltvW5h1lQBGEWE43Fu1NG0S1ab8NKQa99WKbrgIIEtVfZuoVktMh2X0CHMI2H0TIy62hnOEp0+++j7vlAg8iNKIQczzb5FGAx2NgwDqwG7GGMXVyJ1gCLWIUamcBMgtH57yYj4vhWXhYdu6SXj76op+AHlLq3VhJ3b0YnVLZi33FsI0uFqbRkye/OlH4GjvBfrq0FvrGkOmVIIDApMx4g8fV/JaRKBZHNG/7BV+O4XmXJU7Vnlb7EUayOZErnfKNGtiW/epcq6zoxOrs7qVPeIvA6u0Lo4aNK2I69uIUnrTosEbHdrLTax0dR29NgTO03kcnBYRUJjZodsrv9V3WD0FI=
  template:
    metadata:
      creationTimestamp: null
      name: hedgedoc-secrets
      namespace: verein-int
