apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aoc-leaderboard-scraper-data
  namespace: verein-int
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi

