apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: aoc-leaderboard-scraper
  namespace: flux-system
spec:
  image: ghcr.io/neuland-ingolstadt/aoc-leaderboard-scraper
  interval: 10m
  secretRef:
    name: ghcr-secret
