---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authentik
  namespace: verein-int
spec:
  interval: 24h
  url: https://charts.goauthentik.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: verein-int
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: verein-int
      interval: 12h
  values:
    # Core authentik configuration
    authentik:
      secret_key: ""  # Will be set via environment variable
      # Error reporting configuration
      error_reporting:
        enabled: false
    
    # Server configuration with ingress
    server:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - auth.eggl.one
        tls:
          - hosts:
              - auth.eggl.one
            secretName: eggl-one-wildcard-tls
    
    # PostgreSQL configuration
    postgresql:
      enabled: true
      auth:
        password: ""  # Will be set via environment variable
    
    # Redis configuration
    redis:
      enabled: true
    
    # Environment variables to pass secrets from sealed secret
    env:
      - name: AUTHENTIK_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: authentik-secrets
            key: secret-key
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: authentik-secrets
            key: postgres-password

