---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authentik
  namespace: verein-int
spec:
  interval: 24h
  url: https://charts.goauthentik.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: verein-int
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: verein-int
      interval: 12h
  values:
    # Core authentik configuration
    authentik:
      enabled: false  # Disable the chart's secret creation
      secret_key: ""  # Not used since we're using our own secret
      # Error reporting configuration
      error_reporting:
        enabled: false
    
    # Server configuration with ingress
    server:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - auth.eggl.one
        tls:
          - hosts:
              - auth.eggl.one
            secretName: eggl-one-wildcard-tls
      # Use our existing sealed secret
      envFrom:
        - secretRef:
            name: authentik-secrets
    
    # Worker configuration
    worker:
      # Use our existing sealed secret
      envFrom:
        - secretRef:
            name: authentik-secrets
    
    # PostgreSQL configuration
    postgresql:
      enabled: true
      auth:
        password: ""  # Will be set via environment variable from sealed secret
    
    # Redis configuration
    redis:
      enabled: true

