apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authentik
  namespace: verein-int
spec:
  interval: 24h
  url: https://charts.goauthentik.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: verein-int
spec:
  interval: 30m
  targetNamespace: verein-int
  valuesFrom:
    - kind: Secret
      name: authentik-secrets
      valuesKey: secret-key
      targetPath: authentik.secret_key
    - kind: Secret
      name: authentik-secrets
      valuesKey: postgres-password
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: authentik-secrets
      valuesKey: postgres-password
      targetPath: postgresql.auth.password
    - kind: Secret
      name: authentik-secrets
      valuesKey: AUTHENTIK_EMAIL__HOST
      targetPath: authentik.email.host
    - kind: Secret
      name: authentik-secrets
      valuesKey: AUTHENTIK_EMAIL__USERNAME
      targetPath: authentik.email.username
    - kind: Secret
      name: authentik-secrets
      valuesKey: AUTHENTIK_EMAIL__PASSWORD
      targetPath: authentik.email.password
    - kind: Secret
      name: authentik-secrets
      valuesKey: AUTHENTIK_EMAIL__FROM
      targetPath: authentik.email.from
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: verein-int
      interval: 12h
  values:
    authentik:
      log_level: warning
      storage:
        media:
          backend: local
          local:
            path: /media
      email:
        port: 587
        use_tls: true
        use_ssl: false
        timeout: 10
      error_reporting:
        enabled: false
    server:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - auth.neuland.ing
        tls:
          - hosts:
              - auth.neuland.ing
            secretName: authentik-tls
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: authentik-media
      volumeMounts:
        - name: media
          mountPath: /media
    postgresql:
      enabled: true
      primary:
        persistence:
          enabled: true
          existingClaim: authentik-postgresql-0
          # size: 2Gi  # Not needed when using existingClaim
          # storageClassName: longhorn  # Not needed when using existingClaim
    worker:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: authentik-media
      volumeMounts:
        - name: media
          mountPath: /media
