---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authentik
  namespace: verein-int
spec:
  interval: 24h
  url: https://charts.goauthentik.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: verein-int
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: verein-int
      interval: 12h
  values:
    authentik:
      error_reporting:
        enabled: false
    server:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - auth.neuland.ing
        tls:
          - hosts:
              - auth.neuland.ing
            secretName: authentik-tls
      extraEnv:
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: secret-key
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: postgres-password
    worker:
      extraEnv:
        - name: AUTHENTIK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: secret-key
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-secrets
              key: postgres-password
    postgresql:
      enabled: true
      auth:
        existingSecret: authentik-secrets
        secretKeys:
          adminPasswordKey: postgres-password
      primary:
        persistence:
          enabled: false
