apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: neuland-next-docs
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/cluster/apps/neuland-app/neuland-next-docs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  images:
    - name: ghcr.io/neuland-ingolstadt/neuland.app-docs
      newTag: build-34 # {"$imagepolicy": "flux-system:neuland-next-docs:tag"}
  wait: true
