---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neuland-api-staging
  namespace: neuland-app
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - api.dev.eggl.one
    secretName: eggl-one-wildcard-tls
  rules:
  - host: api.dev.eggl.one
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: neuland-api-staging
            port:
              number: 4000
