apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  finalizers:
    - finalizers.fluxcd.io
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 1h0m0s
  provider: generic
  url: https://bitnami-labs.github.io/sealed-secrets
