apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: twin
  namespace: monitoring
spec:
  url: https://twin.github.io/helm-charts/
  interval: 24h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: gatus
      version: "1.4.4"
      sourceRef:
        kind: HelmRepository
        name: twin
        namespace: monitoring
      interval: 12h
  values:
    image:
      repository: twinproduction/gatus
      tag: "v5.33.1"
    replicaCount: 1
    persistence:
      enabled: true
      size: 200Mi
      storageClassName: longhorn
    deploymentStrategy:
      type: Recreate
    service:
      enabled: true
      type: ClusterIP
      port: 80
      targetPort: 8080
    config:
      storage:
        type: sqlite
        path: /data/gatus.db
      connectivity:
        checker:
          target: 1.1.1.1:53
          interval: 60s
      alerting:
        telegram:
          enabled: true
          token: "${TELEGRAM_BOT_TOKEN}"
          id: -1003368636870
        discord:
          enabled: true
          webhook-url: "${DISCORD_WEBHOOK_URL}"
      ui:
        dark-mode: true
        default-sort-by: group
        title: "Neuland Services Status"
        description: "Service and application health monitoring for Neuland Ingolstadt."
        dashboard-heading: "Neuland Services"
        dashboard-subheading: "Real-time monitoring of all Neuland services and applications."
        header: "Neuland Ingolstadt"
        logo: "https://neuland-ingolstadt.de/favicon.png"
        buttons:
          - name: "Neuland Website"
            link: "https://neuland-ingolstadt.de"
          - name: "Impressum"
            link: "https://neuland-ingolstadt.de/legal/impressum"
          - name: "Datenschutz"
            link: "https://neuland-ingolstadt.de/legal/datenschutz"
      announcements:
        - timestamp: 2025-12-29T14:00:00+01:00
          type: outage
          message: "Authentik is currently unable to provide account data and authentication services due to database connectivity issues."
          archived: true
        - timestamp: 2025-12-29T14:30:00+01:00
          type: operational
          message: "Authentik is now available and functioning normally again."
          archived: true
        - timestamp: 2025-12-29T03:00:00+01:00
          type: outage
          message: "All services are currently unavailable due to planned maintenance of the ingress controller."
          archived: true
        - timestamp: 2025-12-29T04:16:00+01:00
          type: operational
          message: "Planned maintenance completed successfully. All services are now available again."
          archived: true
        - timestamp: 2025-12-18T17:00:00Z
          type: warning
          message: "Scheduled maintenance (server upgrades) today 18:00–22:00 (Europe/Berlin). Some services may be unavailable, including login/SSO."
          archived: true
        - timestamp: 2025-12-18T22:00:00Z
          type: information
          message: "Neuland Member ID: Due to new authentication system, the login in Neuland Next is currently unavailable. We are working on an app update to fix this."
          archived: true
        - timestamp: 2025-12-18T22:10:00Z
          type: operational
          message: "Upgrades completed successfully. Authentik is now available on its new domain: https://auth.neuland.ing"
          archived: true
        - timestamp: 2025-12-24T18:00:00Z
          type: information
          message: "The Advent of Code leaderboard has been shut down now that the event has ended. See you next year!"
          archived: true
      default-endpoint: &defaults
        interval: 1m
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: telegram
            send-on-resolved: true
          - type: discord
            send-on-resolved: true
      endpoints:
        # Neuland Next Services
        - name: Neuland Next Web
          !!merge <<: *defaults
          group: Neuland App
          url: "https://web.neuland.app"

        - name: Neuland Next Landing Page
          !!merge <<: *defaults
          group: Neuland App
          url: "https://neuland.app"

        - name: Neuland Next Web (Beta)
          !!merge <<: *defaults
          group: Neuland App
          url: "https://dev.neuland.app"

        - name: Neuland API
          !!merge <<: *defaults
          group: Neuland App
          url: "https://api.neuland.app/graphql"
          method: POST
          headers:
            Content-Type: "application/json"
          body: |
            {
                "query": "query { __typename }"
            }

        - name: Neuland API (Beta)
          !!merge <<: *defaults
          group: Neuland App
          url: "https://api.dev.neuland.app/graphql"
          method: POST
          headers:
            Content-Type: "application/json"
          body: |
            {
                "query": "query { __typename }"
            }

        - name: Neuland API Dashboard
          !!merge <<: *defaults
          group: Verein (Internal)
          url: "https://dashboard.neuland.app"

        - name: Ersti-Kit
          !!merge <<: *defaults
          group: Ersti-Kit
          url: "https://ersti.neuland.app"

        - name: Map Server
          !!merge <<: *defaults
          group: Neuland App
          url: "https://tile.neuland.app/health"

        # Neuland Verein Services
        - name: Neuland Website
          !!merge <<: *defaults
          group: Verein (Public)
          url: "https://neuland-ingolstadt.de"

        - name: Member ID Scanner
          !!merge <<: *defaults
          group: Verein (Public)
          url: "https://id.neuland-ingolstadt.de"

        - name: Member ID API
          !!merge <<: *defaults
          group: Verein (Public)
          url: "https://id.neuland-ingolstadt.de/api/health"

        - name: Neuland Notes
          !!merge <<: *defaults
          group: Verein (Internal)
          url: "https://notes.neuland-ingolstadt.de"
          ui:
            hide-url: true
            hide-hostname: true

        - name: Ist Informatik sexy?
          !!merge <<: *defaults
          group: Verein (Public)
          url: "https://ist.informatik.sexy"

        - name: Authentik
          !!merge <<: *defaults
          group: Verein (Internal)
          url: "https://auth.neuland.ing"
          ui:
            hide-url: true
            hide-hostname: true

        - name: Nextcloud
          !!merge <<: *defaults
          group: Verein (Internal)
          url: "https://cloud.informatik.sexy/status.php"
          ui:
            hide-url: true
            hide-hostname: true

        - name: Campus Life Dashboard
          !!merge <<: *defaults
          group: Campus Life
          url: "https://cl.neuland-ingolstadt.de"

        - name: Campus Life API
          !!merge <<: *defaults
          group: Campus Life
          url: "https://cl.neuland-ingolstadt.de/api/v1/healthcheck"

        # External Dependencies
        - name: THI-API
          !!merge <<: *defaults
          group: Neuland App
          url: "https://hiplan.thi.de/webservice/zits_s_40_test/index.php"
          method: POST
          interval: 5m
          headers:
            Content-Type: "application/x-www-form-urlencoded"
          body: "service=session&method=open&format=json"
          conditions:
            - "[STATUS] == 200"
            - "[CERTIFICATE_EXPIRATION] > 48h"
          ui:
            hide-url: true
            hide-hostname: true

    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
    env:
      TELEGRAM_BOT_TOKEN:
        valueFrom:
          secretKeyRef:
            name: telegram-bot-secrets
            key: TELEGRAM_BOT_API_KEY
      DISCORD_WEBHOOK_URL:
        valueFrom:
          secretKeyRef:
            name: discord-monitoring-webhook
            key: DISCORD_WEBHOOK_URL
    podTemplate:
      spec:
        dnsPolicy: "ClusterFirst"
        terminationGracePeriodSeconds: 30
