apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: student-verification
  namespace: verein-int
spec:
  secretName: student-verification-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - verification.neuland-ingolstadt.de
