---
apiVersion: v1
kind: Namespace
metadata:
  name: hcloud-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: hcloud-ip-floater
  namespace: hcloud-system
spec:
  image: ghcr.io/costela/hcloud-ip-floater
  interval: 10m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: hcloud-ip-floater
  namespace: hcloud-system
spec:
  imageRepositoryRef:
    name: hcloud-ip-floater
  policy:
    semver:
      range: ">=0.1.0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcloud-ip-floater
  namespace: hcloud-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: hcloud-ip-floater
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hcloud-ip-floater
    spec:
      serviceAccountName: hcloud-ip-floater
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - hcloud-ip-floater
              topologyKey: kubernetes.io/hostname
      containers:
      - name: hcloud-ip-floater
        image: ghcr.io/costela/hcloud-ip-floater:0.1.6 # {"$imagepolicy": "hcloud-system:hcloud-ip-floater:tag"}
        env:
        - name: HCLOUD_IP_FLOATER_HCLOUD_TOKEN
          valueFrom:
            secretKeyRef:
              name: hcloud-token
              key: token
        - name: HCLOUD_IP_FLOATER_LOG_LEVEL
          value: "info"
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 64Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hcloud-ip-floater
  namespace: hcloud-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hcloud-ip-floater
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hcloud-ip-floater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hcloud-ip-floater
subjects:
- kind: ServiceAccount
  name: hcloud-ip-floater
  namespace: hcloud-system

