---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: reflector
  namespace: flux-system
spec:
  interval: 10m
  url: https://emberstack.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: cert-manager
spec:
  interval: 10m
  chart:
    spec:
      chart: reflector
      version: "7.1.262"
      sourceRef:
        kind: HelmRepository
        name: reflector
        namespace: flux-system
  values:
    # Reflector automatically copies secrets/configmaps between namespaces
    nameOverride: "reflector"
    fullnameOverride: "reflector"
    
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
    
    configuration:
      resyncPeriod: 150
      watchNamespaces: ["cert-manager", "neuland-app", "verein-ext", "monitoring"]
    
    logLevel: "info"
    