apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sops-infra
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: sops-infra-auth
  url: https://github.com/neuland-ingolstadt/sops-infra
