apiVersion: v1
kind: Service
metadata:
  name: neuland-shared-db
  namespace: neuland-app
spec:
  type: ClusterIP
  selector:
    app: neuland-shared-db
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: postgres
