apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neuland-shared-database-pvc
  namespace: neuland-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
