apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: neuland-website
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/cluster/apps/verein-ext/neuland-website
  images:
    - name: ghcr.io/neuland-ingolstadt/neuland-website
      newTag: build-152 # {"$imagepolicy": "flux-system:neuland-website:tag"}
  wait: true
