apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuland-website
  namespace: verein-ext
spec:
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: neuland-website
  template:
    metadata:
      labels:
        app: neuland-website
    spec:
      containers:
      - name: neuland-website
        image: ghcr.io/neuland-ingolstadt/neuland-website:build-167 # {"$imagepolicy": "flux-system:neuland-website"}
        imagePullPolicy: IfNotPresent
        env:
        - name: HOSTNAME
          value: 0.0.0.0
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: production
        - name: OUTLINE_API_KEY
          valueFrom:
            secretKeyRef:
              name: neuland-website-secrets
              key: OUTLINE_API_KEY
        - name: CL_API_KEY
          valueFrom:
            secretKeyRef:
              name: neuland-website-secrets
              key: CL_API_KEY
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
