apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: neuland-website
  namespace: verein-ext
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: neuland-website
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70