apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: neuland-website
  namespace: flux-system
spec:
  image: ghcr.io/neuland-ingolstadt/neuland-website
  interval: 10m
  secretRef:
    name: ghcr-secret
