---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eggl-one-wildcard
  namespace: cert-manager
spec:
  secretName: eggl-one-wildcard-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
  - eggl.one
  - "*.eggl.one"
