---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eggl-one-wildcard
  namespace: cert-manager
  annotations:
    # Reflector will copy this certificate to other namespaces
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "neuland-app,verein-ext"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
spec:
  secretName: eggl-one-wildcard-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "neuland-app,verein-ext"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  # List specific domains instead of wildcards - works with HTTP-01 challenges
  dnsNames:
  - eggl.one
  - app.eggl.one
  - docs.app.eggl.one
  - dev.app.eggl.one
  - ersti.eggl.one
  - dev.ersti.eggl.one
