---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: oauth2-proxy
  ports:
  - name: http
    port: 4180
    targetPort: 4180

