apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: neuland-next-staging
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/cluster/apps/neuland-app/neuland-next-staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  images:
    - name: ghcr.io/neuland-ingolstadt/neuland.app-native/webapp
      newTag: staging-179 # {"$imagepolicy": "flux-system:neuland-next-staging:tag"}
  wait: true

