apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: neuland-next-staging
  namespace: flux-system
spec:
  interval: 1m
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: neuland.app-native
  images:
    - name: ghcr.io/neuland-ingolstadt/neuland.app-native/webapp
      newTag: staging-176
  targetNamespace: neuland-app
  wait: true
  patches:
    - target:
        kind: ImageRepository
        name: neuland-next-staging
      patch: |
        - op: add
          path: /spec/secretRef
          value:
            name: ghcr-secret
