---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neuland-next-staging
  namespace: neuland-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - dev.app.eggl.one
    secretName: eggl-one-wildcard-tls
  rules:
  - host: dev.app.eggl.one
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: neuland-next-staging
            port:
              number: 3000
