apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Receiver
metadata:
  name: github-webhook
  namespace: flux-system
spec:
  type: github
  secretRef:
    name: github-webhook-secret
  resources:
    - kind: GitRepository
      name: flux-system
    - kind: Kustomization
      name: flux-system
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flux-webhook-receiver
  namespace: flux-system
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - flux-webhook.neuland.ing
    secretName: flux-system-webhook-tls
  rules:
  - host: flux-webhook.neuland.ing
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webhook-receiver
            port:
              number: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flux-webhook-tls
  namespace: flux-system
spec:
  secretName: flux-system-webhook-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - flux-webhook.neuland.ing

