---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin-lite
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "false"
rules:
  # Allow watching most core resources (needed for k9s)
  - apiGroups: [""]
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - limitranges
      - resourcequotas
      - namespaces
      - nodes
      - persistentvolumes
    verbs: ["get", "list", "watch"]
  
  # Allow watching apps resources
  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs: ["get", "list", "watch"]
  
  # Allow watching batch resources
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]
  
  # Allow watching networking resources
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
      - networkpolicies
    verbs: ["get", "list", "watch"]
  
  # Allow watching storage resources
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
    verbs: ["get", "list", "watch"]
  
  # Allow watching autoscaling resources
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch"]
  
  # Allow watching policy resources
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs: ["get", "list", "watch"]
  
  # Allow watching Flux resources (read-only)
  - apiGroups:
      - source.toolkit.fluxcd.io
      - kustomize.toolkit.fluxcd.io
      - helm.toolkit.fluxcd.io
      - image.toolkit.fluxcd.io
      - notification.toolkit.fluxcd.io
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  
  # Allow reading pod logs (useful for debugging but safe)
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
  
  # Note: Secrets are explicitly NOT included in any rule above, so access is denied
  # Note: pods/exec and pods/portforward subresources are NOT included, so they are denied
  # Note: For additional CRDs, add them explicitly here rather than using wildcards

