apiVersion: batch/v1
kind: CronJob
metadata:
  name: mensa-xml-scraper
  namespace: neuland-app
spec:
  # Every hour
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mensa-xml-scraper
              image: amazon/aws-cli:2.15.0
              imagePullPolicy: IfNotPresent
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: hetzner-s3-secret
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: hetzner-s3-secret
                      key: AWS_SECRET_ACCESS_KEY
                - name: AWS_ENDPOINT_URL
                  value: https://nbg1.your-objectstorage.com
                - name: AWS_DEFAULT_REGION
                  value: nbg1
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  TS="$(date +%Y-%m-%d-%H:%M:%S)"
                  OUT="/tmp/mensa-ingolstadt-${TS}.xml"
                  
                  echo "Downloading mensa XML file..."
                  curl -fsSL "https://www.max-manager.de/daten-extern/sw-erlangen-nuernberg/xml/mensa-ingolstadt.xml" -o "${OUT}"
                  
                  echo "Uploading to S3..."
                  aws s3 cp "${OUT}" "s3://neuland/mensa-thi/mensa-ingolstadt-${TS}.xml" \
                    --endpoint-url="${AWS_ENDPOINT_URL}" \
                    --region="${AWS_DEFAULT_REGION}"
                  
                  echo "Upload completed: mensa-thi-${TS}.xml"
          restartPolicy: OnFailure
