apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mensa-xml-storage
  namespace: neuland-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
