# Role in longhorn-system namespace to allow reading the secret
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mensa-scraper-secret-reader
  namespace: longhorn-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["longhorn-s3-secret"]
    verbs: ["get"]

---
# RoleBinding to grant the service account access
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mensa-scraper-secret-reader
  namespace: longhorn-system
subjects:
  - kind: ServiceAccount
    name: mensa-scraper
    namespace: neuland-app
roleRef:
  kind: Role
  name: mensa-scraper-secret-reader
  apiGroup: rbac.authorization.k8s.io
