apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: ist-informatik-sexy
  namespace: flux-system
spec:
  image: ghcr.io/neuland-ingolstadt/ist.informatik.sexy
  interval: 30m
  secretRef:
    name: ghcr-secret
