apiVersion: v1
kind: Service
metadata:
  name: pretix-postgres
  namespace: verein-ext
spec:
  type: ClusterIP
  selector:
    app: pretix-postgres
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: postgres
