apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pretix-db-postgres-pvc
  namespace: verein-ext
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
