apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pretix-data-pvc
  namespace: verein-ext
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
